name: Python package

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv and setup Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/uv.lock
          **/pyproject.toml
        python-version: ${{ matrix.python-version }}

    - name: Test with pytest and generate coverage report
      run: |
        uv run --frozen pytest --cov=src --cov-branch --cov-report=xml --cov-report=html:htmlcov tests

    - name: Upload coverage reports to Codecov
      if: ${{ !env.ACT }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: ${{ github.repository }}

    - name: Build distribution packages
      run: uv build --sdist --wheel

    - name: Minimize uv cache
      run: uv cache prune --ci
