name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Install the latest version of uv and setup Python
      uses: astral-sh/setup-uv@v5

    - name: Build distributions
      run: uv build --out-dir dist --sdist --wheel

    - name: Release
      if: ${{ !env.ACT }}
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*
